require 'faraday'
require 'json'
require 'ranger'
require 'paint/pa'

require_relative './api_search/version'
require_relative './api_search/cli'
require_relative './api_search/client'
require_relative './api_search/category'
require_relative './api_search/api'
